AllCops:
  EnabledByDefault: true
  NewCops: enable
  Exclude:
    - '*.txt'
    - '*.md'

Lint/NumberConversion:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Lint/UselessMethodDefinition:
  Enabled: false

Style/StringHashKeys:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/ConstantVisibility:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TopLevelMethodDefinition:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/InlineComment:
  Enabled: false

Style/Copyright:
  Notice: ''
  AutocorrectNotice: ''  


Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/SingleLineBlockChain:
  Enabled: false

Layout/MultilineAssignmentLayout:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false
